name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "next-release"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Must have `next-release` tag to merge to dev"
        BANNED_LABELS: "banned"
